#!/usr/bin/env python3
"""Generate src/lantern_font.h — the built-in 8x8 debug font.

Glyph art is OUR OWN, ported from game/make_chr.py (Rocket Rush's 5x7-in-8
uppercase font, hand-authored 2026-07) plus punctuation added here. Rerun
after editing: python3 tools/gen_font.py  (from engine/).

Output: LT_FONT8[64][8] covering ASCII 32..95 (uppercase-only; the engine
upcases lowercase before lookup). Row byte MSB = leftmost pixel.
"""
import os

F = {
"A":["..XX...",".X..X..","X....X.","X....X.","XXXXXX.","X....X.","X....X."],
"B":["XXXXX..","X....X.","X....X.","XXXXX..","X....X.","X....X.","XXXXX.."],
"C":[".XXXX..","X....X.","X......","X......","X......","X....X.",".XXXX.."],
"D":["XXXXX..","X....X.","X....X.","X....X.","X....X.","X....X.","XXXXX.."],
"E":["XXXXXX.","X......","X......","XXXXX..","X......","X......","XXXXXX."],
"F":["XXXXXX.","X......","X......","XXXXX..","X......","X......","X......"],
"G":[".XXXX..","X....X.","X......","X..XXX.","X....X.","X....X.",".XXXX.."],
"H":["X....X.","X....X.","X....X.","XXXXXX.","X....X.","X....X.","X....X."],
"I":["XXXXX..","..X....","..X....","..X....","..X....","..X....","XXXXX.."],
"J":["..XXXX.","....X..","....X..","....X..","X...X..","X...X..",".XXX..."],
"K":["X...X..","X..X...","X.X....","XX.....","X.X....","X..X...","X...X.."],
"L":["X......","X......","X......","X......","X......","X......","XXXXXX."],
"M":["X....X.","XX..XX.","X.XX.X.","X....X.","X....X.","X....X.","X....X."],
"N":["X....X.","XX...X.","X.X..X.","X..X.X.","X...XX.","X....X.","X....X."],
"O":[".XXXX..","X....X.","X....X.","X....X.","X....X.","X....X.",".XXXX.."],
"P":["XXXXX..","X....X.","X....X.","XXXXX..","X......","X......","X......"],
"Q":[".XXXX..","X....X.","X....X.","X....X.","X..X.X.","X...X..",".XXX.X."],
"R":["XXXXX..","X....X.","X....X.","XXXXX..","X.X....","X..X...","X...X.."],
"S":[".XXXX..","X....X.","X......",".XXXX..","......X","X....X.",".XXXX.."],
"T":["XXXXXXX","...X...","...X...","...X...","...X...","...X...","...X..."],
"U":["X....X.","X....X.","X....X.","X....X.","X....X.","X....X.",".XXXX.."],
"V":["X....X.","X....X.","X....X.","X....X.",".X..X..","..XX...","...X..."],
"W":["X....X.","X....X.","X....X.","X.XX.X.","X.XX.X.","XX..XX.","X....X."],
"X":["X....X.",".X..X..","..XX...","...X...","..XX...",".X..X..","X....X."],
"Y":["X....X.",".X..X..","..XX...","...X...","...X...","...X...","...X..."],
"Z":["XXXXXX.","....X..","...X...","..X....",".X.....","X......","XXXXXX."],
"0":[".XXX...","X...X..","X..XX..","X.X.X..","XX..X..","X...X..",".XXX..."],
"1":["..X....",".XX....","..X....","..X....","..X....","..X....",".XXX..."],
"2":[".XXX...","X...X..","....X..","...X...","..X....",".X.....","XXXXX.."],
"3":["XXXXX..","....X..","...X...","..XX...","....X..","X...X..",".XXX..."],
"4":["...XX..","..X.X..",".X..X..","X...X..","XXXXXX.","....X..","....X.."],
"5":["XXXXX..","X......","XXXX...","....X..","....X..","X...X..",".XXX..."],
"6":["..XX...",".X.....","X......","XXXX...","X...X..","X...X..",".XXX..."],
"7":["XXXXX..","....X..","...X...","..X....",".X.....",".X.....",".X....."],
"8":[".XXX...","X...X..","X...X..",".XXX...","X...X..","X...X..",".XXX..."],
"9":[".XXX...","X...X..","X...X..",".XXXX..","....X..","...X...",".XX...."],
"!":["..X....","..X....","..X....","..X....","..X....",".......","..X...."],
"-":[".......",".......",".......","XXXXXX.",".......",".......","......."],
".":[".......",".......",".......",".......",".......","..XX...","..XX..."],
# ── added for lantern (same 5x7-in-8 style) ──
":":[".......","..XX...","..XX...",".......","..XX...","..XX...","......."],
"?":[".XXX...","X...X..","....X..","...X...","..X....",".......","..X...."],
"/":["......X",".....X.","....X..","...X...","..X....",".X.....","X......"],
"'":["..X....","..X....",".......",".......",".......",".......","......."],
'"':["..X.X..","..X.X..",".......",".......",".......",".......","......."],
",":[".......",".......",".......",".......","..XX...","..X....",".X....."],
"(":["...X...","..X....",".X.....",".X.....",".X.....","..X....","...X..."],
")":["...X...","....X..",".....X.",".....X.",".....X.","....X..","...X..."],
"+":[".......","...X...","...X...",".XXXXX.","...X...","...X...","......."],
"=":[".......",".......","XXXXXX.",".......","XXXXXX.",".......","......."],
"*":[".......","X..X..X",".X.X.X.","..XXX..",".X.X.X.","X..X..X","......."],
"<":["....X..","...X...","..X....",".X.....","..X....","...X...","....X.."],
">":["..X....","...X...","....X..",".....X.","....X..","...X...","..X...."],
}

def glyph_bytes(rows):
    out = []
    for r in range(8):
        row = rows[r] if r < len(rows) else ""
        b = 0
        for c in range(8):
            if c < len(row) and row[c] == "X":
                b |= 0x80 >> c
        out.append(b)
    return out

lines = [
    "// GENERATED by tools/gen_font.py — do not hand-edit. ASCII 32..95,",
    "// uppercase-only 5x7-in-8 font ported from game/make_chr.py (our art).",
    "#pragma once",
    "static const unsigned char LT_FONT8[64][8] = {",
]
for code in range(32, 96):
    ch = chr(code)
    rows = F.get(ch, [])
    b = glyph_bytes(rows)
    # a trailing "\" in a // comment line-continues it and swallows the next
    # array row — name it instead of printing it
    label = {" ": "space", "\\": "backslash"}.get(ch, ch)
    lines.append("    {%s}, // %s" %
                 (",".join("0x%02x" % x for x in b), label))
lines.append("};")

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", "src", "lantern_font.h")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", os.path.normpath(out))
